class InsertarRazaPerros < ActiveRecord::Migration
  def up
    Raza.create(tipo: 'perro', nombre: 'Airedale terrier')
    Raza.create(tipo: 'perro', nombre: 'Akita')
    Raza.create(tipo: 'perro', nombre: 'Akita americano')
    Raza.create(tipo: 'perro', nombre: 'Alaskan Husky')
    Raza.create(tipo: 'perro', nombre: 'Alaskan malamute')
    Raza.create(tipo: 'perro', nombre: 'American Foxhound')
    Raza.create(tipo: 'perro', nombre: 'American pit bull terrier')
    Raza.create(tipo: 'perro', nombre: 'American staffordshire terrier')
    Raza.create(tipo: 'perro', nombre: 'Ariegeois')
    Raza.create(tipo: 'perro', nombre: 'Artois')
    Raza.create(tipo: 'perro', nombre: 'Australian silky terrier')
    Raza.create(tipo: 'perro', nombre: 'Australian Terrier')
    Raza.create(tipo: 'perro', nombre: 'Austrian Black & Tan Hound')
    Raza.create(tipo: 'perro', nombre: 'Azawakh')
    Raza.create(tipo: 'perro', nombre: 'Balkan Hound')
    Raza.create(tipo: 'perro', nombre: 'Basenji')
    Raza.create(tipo: 'perro', nombre: 'Basset Alpino (Alpine Dachsbracke)')
    Raza.create(tipo: 'perro', nombre: 'Basset Artesiano Normando')
    Raza.create(tipo: 'perro', nombre: 'Basset Azul de Gascuña (Basset Bleu de Gascogne)')
    Raza.create(tipo: 'perro', nombre: 'Basset de Artois')
    Raza.create(tipo: 'perro', nombre: 'Basset de Westphalie')
    Raza.create(tipo: 'perro', nombre: 'Basset Hound')
    Raza.create(tipo: 'perro', nombre: 'Basset Leonado de Bretaña (Basset fauve de Bretagne)')
    Raza.create(tipo: 'perro', nombre: 'Bavarian Mountain Scenthound')
    Raza.create(tipo: 'perro', nombre: 'Beagle')
    Raza.create(tipo: 'perro', nombre: 'Beagle Harrier')
    Raza.create(tipo: 'perro', nombre: 'Beauceron')
    Raza.create(tipo: 'perro', nombre: 'Bedlington Terrier')
    Raza.create(tipo: 'perro', nombre: 'Bichon Boloñes')
    Raza.create(tipo: 'perro', nombre: 'Bichón Frisé')
    Raza.create(tipo: 'perro', nombre: 'Bichón Habanero')
    Raza.create(tipo: 'perro', nombre: 'Billy')
    Raza.create(tipo: 'perro', nombre: 'Black and Tan Coonhound')
    Raza.create(tipo: 'perro', nombre: 'Bloodhound (Sabueso de San Huberto)')
    Raza.create(tipo: 'perro', nombre: 'Bobtail')
    Raza.create(tipo: 'perro', nombre: 'Boerboel')
    Raza.create(tipo: 'perro', nombre: 'Border Collie')
    Raza.create(tipo: 'perro', nombre: 'Border terrier')
    Raza.create(tipo: 'perro', nombre: 'Borzoi')
    Raza.create(tipo: 'perro', nombre: 'Bosnian Hound')
    Raza.create(tipo: 'perro', nombre: 'Boston terrier')
    Raza.create(tipo: 'perro', nombre: 'Bouvier des Flandres')
    Raza.create(tipo: 'perro', nombre: 'Boxer')
    Raza.create(tipo: 'perro', nombre: 'Boyero de Appenzell')
    Raza.create(tipo: 'perro', nombre: 'Boyero de Australia')
    Raza.create(tipo: 'perro', nombre: 'Boyero de Entlebuch')
    Raza.create(tipo: 'perro', nombre: 'Boyero de las Ardenas')
    Raza.create(tipo: 'perro', nombre: 'Boyero de Montaña Bernes')
    Raza.create(tipo: 'perro', nombre: 'Braco Alemán de pelo corto')
    Raza.create(tipo: 'perro', nombre: 'Braco Alemán de pelo duro')
    Raza.create(tipo: 'perro', nombre: 'Braco de Ariege')
    Raza.create(tipo: 'perro', nombre: 'Braco de Auvernia')
    Raza.create(tipo: 'perro', nombre: 'Braco de Bourbonnais')
    Raza.create(tipo: 'perro', nombre: 'Braco de Saint Germain')
    Raza.create(tipo: 'perro', nombre: 'Braco Dupuy')
    Raza.create(tipo: 'perro', nombre: 'Braco Francés')
    Raza.create(tipo: 'perro', nombre: 'Braco Italiano')
    Raza.create(tipo: 'perro', nombre: 'Broholmer')
    Raza.create(tipo: 'perro', nombre: 'Buhund Noruego')
    Raza.create(tipo: 'perro', nombre: 'Bull terrier')
    Raza.create(tipo: 'perro', nombre: 'Bulldog americano')
    Raza.create(tipo: 'perro', nombre: 'Bulldog inglés')
    Raza.create(tipo: 'perro', nombre: 'Bulldog francés')
    Raza.create(tipo: 'perro', nombre: 'Bullmastiff')
    Raza.create(tipo: 'perro', nombre: 'Ca de Bestiar')
    Raza.create(tipo: 'perro', nombre: 'Cairn terrier')
    Raza.create(tipo: 'perro', nombre: 'Cane Corso')
    Raza.create(tipo: 'perro', nombre: 'Cane da Pastore Maremmano-Abruzzese')
    Raza.create(tipo: 'perro', nombre: 'Caniche (Poodle)')
    Raza.create(tipo: 'perro', nombre: 'Caniche Toy (Toy Poodle)')
    Raza.create(tipo: 'perro', nombre: 'Cao da Serra de Aires')
    Raza.create(tipo: 'perro', nombre: 'Cao da Serra de Estrela')
    Raza.create(tipo: 'perro', nombre: 'Cao de Castro Laboreiro')
    Raza.create(tipo: 'perro', nombre: 'Cao de Fila de Sao Miguel')
    Raza.create(tipo: 'perro', nombre: 'Cavalier King Charles Spaniel')
    Raza.create(tipo: 'perro', nombre: 'Cesky Fousek')
    Raza.create(tipo: 'perro', nombre: 'Cesky Terrier')
    Raza.create(tipo: 'perro', nombre: 'Chesapeake Bay Retriever')
    Raza.create(tipo: 'perro', nombre: 'Chihuahua')
    Raza.create(tipo: 'perro', nombre: 'Chin')
    Raza.create(tipo: 'perro', nombre: 'Chow Chow')
    Raza.create(tipo: 'perro', nombre: 'Cirneco del Etna')
    Raza.create(tipo: 'perro', nombre: 'Clumber Spaniel')
    Raza.create(tipo: 'perro', nombre: 'Cocker Spaniel Americano')
    Raza.create(tipo: 'perro', nombre: 'Cocker Spaniel Inglés')
    Raza.create(tipo: 'perro', nombre: 'Collie Barbudo')
    Raza.create(tipo: 'perro', nombre: 'Collie de Pelo Corto')
    Raza.create(tipo: 'perro', nombre: 'Collie de Pelo Largo')
    Raza.create(tipo: 'perro', nombre: 'Cotón de Tuléar')
    Raza.create(tipo: 'perro', nombre: 'Curly Coated Retriever')
    Raza.create(tipo: 'perro', nombre: 'Dálmata')
    Raza.create(tipo: 'perro', nombre: 'Dandie dinmont terrier')
    Raza.create(tipo: 'perro', nombre: 'Deerhound')
    Raza.create(tipo: 'perro', nombre: 'Dobermann')
    Raza.create(tipo: 'perro', nombre: 'Dogo Argentino')
    Raza.create(tipo: 'perro', nombre: 'Dogo de Burdeos')
    Raza.create(tipo: 'perro', nombre: 'Dogo del Tibet')
    Raza.create(tipo: 'perro', nombre: 'Drentse Partridge Dog')
    Raza.create(tipo: 'perro', nombre: 'Drever')
    Raza.create(tipo: 'perro', nombre: 'Dunker')
    Raza.create(tipo: 'perro', nombre: 'Elkhound Noruego')
    Raza.create(tipo: 'perro', nombre: 'Elkhound Sueco')
    Raza.create(tipo: 'perro', nombre: 'English Foxhound')
    Raza.create(tipo: 'perro', nombre: 'English Springer Spaniel')
    Raza.create(tipo: 'perro', nombre: 'English Toy Terrier')
    Raza.create(tipo: 'perro', nombre: 'Epagneul Picard')
    Raza.create(tipo: 'perro', nombre: 'Eurasier')
    Raza.create(tipo: 'perro', nombre: 'Fila Brasileiro')
    Raza.create(tipo: 'perro', nombre: 'Finnish Lapphound')
    Raza.create(tipo: 'perro', nombre: 'Flat Coated Retriever')
    Raza.create(tipo: 'perro', nombre: 'Fox terrier de pelo de alambre')
    Raza.create(tipo: 'perro', nombre: 'Fox terrier de pelo liso')
    Raza.create(tipo: 'perro', nombre: 'Foxhound Inglés')
    Raza.create(tipo: 'perro', nombre: 'Frisian Pointer')
    Raza.create(tipo: 'perro', nombre: 'Galgo Español')
    Raza.create(tipo: 'perro', nombre: 'Galgo húngaro (Magyar Agar)')
    Raza.create(tipo: 'perro', nombre: 'Galgo Italiano')
    Raza.create(tipo: 'perro', nombre: 'Galgo Polaco (Chart Polski)')
    Raza.create(tipo: 'perro', nombre: 'Glen of Imaal Terrier')
    Raza.create(tipo: 'perro', nombre: 'Golden Retriever')
    Raza.create(tipo: 'perro', nombre: 'Gordon Setter')
    Raza.create(tipo: 'perro', nombre: 'Gos dAtura Catalá')
    Raza.create(tipo: 'perro', nombre: 'Gran Basset Griffon Vendeano')
    Raza.create(tipo: 'perro', nombre: 'Gran Boyero Suizo')
    Raza.create(tipo: 'perro', nombre: 'Gran Danés (Dogo Aleman)')
    Raza.create(tipo: 'perro', nombre: 'Gran Gascón Saintongeois')
    Raza.create(tipo: 'perro', nombre: 'Gran Griffon Vendeano')
    Raza.create(tipo: 'perro', nombre: 'Gran Munsterlander')
    Raza.create(tipo: 'perro', nombre: 'Gran Perro Japonés')
    Raza.create(tipo: 'perro', nombre: 'Grand Anglo Francais Tricoleur')
    Raza.create(tipo: 'perro', nombre: 'Grand Bleu de Gascogne')
    Raza.create(tipo: 'perro', nombre: 'Greyhound')
    Raza.create(tipo: 'perro', nombre: 'Griffon Bleu de Gascogne')
    Raza.create(tipo: 'perro', nombre: 'Griffon de pelo duro (Grifón Korthals)')
    Raza.create(tipo: 'perro', nombre: 'Griffon leonado de Bretaña')
    Raza.create(tipo: 'perro', nombre: 'Griffon Nivernais')
    Raza.create(tipo: 'perro', nombre: 'Grifon Belga')
    Raza.create(tipo: 'perro', nombre: 'Grifón de Bruselas')
    Raza.create(tipo: 'perro', nombre: 'Haldenstoever')
    Raza.create(tipo: 'perro', nombre: 'Harrier')
    Raza.create(tipo: 'perro', nombre: 'Hokkaido')
    Raza.create(tipo: 'perro', nombre: 'Hovawart')
    Raza.create(tipo: 'perro', nombre: 'Husky Siberiano (Siberian Husky)')
    Raza.create(tipo: 'perro', nombre: 'Ioujnorousskaia Ovtcharka')
    Raza.create(tipo: 'perro', nombre: 'Irish Glen of Imaal terrier')
    Raza.create(tipo: 'perro', nombre: 'Irish soft coated wheaten terrier')
    Raza.create(tipo: 'perro', nombre: 'Irish terrier')
    Raza.create(tipo: 'perro', nombre: 'Irish Water Spaniel')
    Raza.create(tipo: 'perro', nombre: 'Irish Wolfhound')
    Raza.create(tipo: 'perro', nombre: 'Jack Russell terrier')
    Raza.create(tipo: 'perro', nombre: 'Jindo Coreano')
    Raza.create(tipo: 'perro', nombre: 'Kai')
    Raza.create(tipo: 'perro', nombre: 'Keeshond')
    Raza.create(tipo: 'perro', nombre: 'Kelpie australiano (Australian kelpie)')
    Raza.create(tipo: 'perro', nombre: 'Kerry blue terrier')
    Raza.create(tipo: 'perro', nombre: 'King Charles Spaniel')
    Raza.create(tipo: 'perro', nombre: 'Kishu')
    Raza.create(tipo: 'perro', nombre: 'Komondor')
    Raza.create(tipo: 'perro', nombre: 'Kooiker')
    Raza.create(tipo: 'perro', nombre: 'Kromfohrländer')
    Raza.create(tipo: 'perro', nombre: 'Kuvasz')
    Raza.create(tipo: 'perro', nombre: 'Labrador Retriever')
    Raza.create(tipo: 'perro', nombre: 'Lagotto Romagnolo')
    Raza.create(tipo: 'perro', nombre: 'Laika de Siberia Occidental')
    Raza.create(tipo: 'perro', nombre: 'Laika de Siberia Oriental')
    Raza.create(tipo: 'perro', nombre: 'Laika Ruso Europeo')
    Raza.create(tipo: 'perro', nombre: 'Lakeland terrier')
    Raza.create(tipo: 'perro', nombre: 'Landseer')
    Raza.create(tipo: 'perro', nombre: 'Lapphund Sueco')
    Raza.create(tipo: 'perro', nombre: 'Lebrel Afgano')
    Raza.create(tipo: 'perro', nombre: 'Lebrel Arabe (Sloughi)')
    Raza.create(tipo: 'perro', nombre: 'Leonberger')
    Raza.create(tipo: 'perro', nombre: 'Lhasa Apso')
    Raza.create(tipo: 'perro', nombre: 'Lowchen (Pequeño Perro León)')
    Raza.create(tipo: 'perro', nombre: 'Lundehund Noruego')
    Raza.create(tipo: 'perro', nombre: 'Malamute de Alaska')
    Raza.create(tipo: 'perro', nombre: 'Maltés')
    Raza.create(tipo: 'perro', nombre: 'Manchester terrier')
    Raza.create(tipo: 'perro', nombre: 'Mastiff')
    Raza.create(tipo: 'perro', nombre: 'Mastín de los Pirineos')
    Raza.create(tipo: 'perro', nombre: 'Mastín Español')
    Raza.create(tipo: 'perro', nombre: 'Mastín Napolitano')
    Raza.create(tipo: 'perro', nombre: 'Mudi')
    Raza.create(tipo: 'perro', nombre: 'Norfolk terrier')
    Raza.create(tipo: 'perro', nombre: 'Norwich terrier')
    Raza.create(tipo: 'perro', nombre: 'Nova Scotia duck tolling retriever')
    Raza.create(tipo: 'perro', nombre: 'Ovejero alemán')
    Raza.create(tipo: 'perro', nombre: 'Otterhound')
    Raza.create(tipo: 'perro', nombre: 'Rafeiro do Alentejo')
    Raza.create(tipo: 'perro', nombre: 'Ratonero Bodeguero Andaluz')
    Raza.create(tipo: 'perro', nombre: 'Retriever de Nueva Escocia')
    Raza.create(tipo: 'perro', nombre: 'Rhodesian Ridgeback')
    Raza.create(tipo: 'perro', nombre: 'Ridgeback de Tailandia')
    Raza.create(tipo: 'perro', nombre: 'Rottweiler')
    Raza.create(tipo: 'perro', nombre: 'Saarloos')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Hamilton')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Hannover')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Hygen')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Istria')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Posavaz')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Schiller (Schillerstovare)')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Smaland (Smalandsstovare)')
    Raza.create(tipo: 'perro', nombre: 'Sabueso de Transilvania')
    Raza.create(tipo: 'perro', nombre: 'Sabueso del Tirol')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Español')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Estirio de pelo duro')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Finlandés')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Francés blanco y negro')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Francés tricolor')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Griego')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Polaco (Ogar Polski)')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Serbio')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Suizo')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Yugoslavo de Montaña')
    Raza.create(tipo: 'perro', nombre: 'Sabueso Yugoslavo tricolor')
    Raza.create(tipo: 'perro', nombre: 'Saluki')
    Raza.create(tipo: 'perro', nombre: 'Samoyedo')
    Raza.create(tipo: 'perro', nombre: 'San Bernardo')
    Raza.create(tipo: 'perro', nombre: 'Sarplaninac')
    Raza.create(tipo: 'perro', nombre: 'Schapendoes')
    Raza.create(tipo: 'perro', nombre: 'Schipperke')
    Raza.create(tipo: 'perro', nombre: 'Schnauzer estándar')
    Raza.create(tipo: 'perro', nombre: 'Schnauzer gigante (Riesenschnauzer)')
    Raza.create(tipo: 'perro', nombre: 'Schnauzer miniatura (Zwergschnauzer)')
    Raza.create(tipo: 'perro', nombre: 'Scottish terrier')
    Raza.create(tipo: 'perro', nombre: 'Sealyham terrier')
    Raza.create(tipo: 'perro', nombre: 'Segugio Italiano')
    Raza.create(tipo: 'perro', nombre: 'Seppala Siberiano')
    Raza.create(tipo: 'perro', nombre: 'Setter Inglés')
    Raza.create(tipo: 'perro', nombre: 'Setter Irlandés')
    Raza.create(tipo: 'perro', nombre: 'Setter Irlandés rojo y blanco')
    Raza.create(tipo: 'perro', nombre: 'Shar Pei')
    Raza.create(tipo: 'perro', nombre: 'Shiba Inu')
    Raza.create(tipo: 'perro', nombre: 'Shih Tzu')
    Raza.create(tipo: 'perro', nombre: 'Shikoku')
    Raza.create(tipo: 'perro', nombre: 'Skye terrier')
    Raza.create(tipo: 'perro', nombre: 'Slovensky Cuvac')
    Raza.create(tipo: 'perro', nombre: 'Slovensky Kopov')
    Raza.create(tipo: 'perro', nombre: 'Smoushond Holandés')
    Raza.create(tipo: 'perro', nombre: 'Spaniel Alemán (German Wachtelhund)')
    Raza.create(tipo: 'perro', nombre: 'Spaniel Azul de Picardía')
    Raza.create(tipo: 'perro', nombre: 'Spaniel Bretón')
    Raza.create(tipo: 'perro', nombre: 'Spaniel de Campo')
    Raza.create(tipo: 'perro', nombre: 'Spaniel de Pont Audemer')
    Raza.create(tipo: 'perro', nombre: 'Spaniel Francés')
    Raza.create(tipo: 'perro', nombre: 'Spaniel Tibetano')
    Raza.create(tipo: 'perro', nombre: 'Spinone Italiano')
    Raza.create(tipo: 'perro', nombre: 'Spítz Alemán')
    Raza.create(tipo: 'perro', nombre: 'Spitz de Norbotten (Norbottenspets)')
    Raza.create(tipo: 'perro', nombre: 'Spitz Finlandés')
    Raza.create(tipo: 'perro', nombre: 'Spitz Japonés')
    Raza.create(tipo: 'perro', nombre: 'Staffordshire bull terrier')
    Raza.create(tipo: 'perro', nombre: 'Staffordshire terrier americano')
    Raza.create(tipo: 'perro', nombre: 'Sussex Spaniel')
    Raza.create(tipo: 'perro', nombre: 'Teckel (Dachshund)')
    Raza.create(tipo: 'perro', nombre: 'Tchuvatch eslovaco')
    Raza.create(tipo: 'perro', nombre: 'Terranova (Newfoundland)')
    Raza.create(tipo: 'perro', nombre: 'Terrier australiano (Australian terrier)')
    Raza.create(tipo: 'perro', nombre: 'Terrier brasilero')
    Raza.create(tipo: 'perro', nombre: 'Terrier cazador alemán')
    Raza.create(tipo: 'perro', nombre: 'Terrier checo (Ceský teriér)')
    Raza.create(tipo: 'perro', nombre: 'Terrier galés')
    Raza.create(tipo: 'perro', nombre: 'Terrier irlandés (Irish terrier)')
    Raza.create(tipo: 'perro', nombre: 'Terrier japonés (Nihon teria)')
    Raza.create(tipo: 'perro', nombre: 'Terrier negro ruso')
    Raza.create(tipo: 'perro', nombre: 'Terrier tibetano')
    Raza.create(tipo: 'perro', nombre: 'Tosa')
    Raza.create(tipo: 'perro', nombre: 'Viejo Pastor Inglés')
    Raza.create(tipo: 'perro', nombre: 'Viejo Pointer Danés (Old Danish Pointer)')
    Raza.create(tipo: 'perro', nombre: 'Vizsla')
    Raza.create(tipo: 'perro', nombre: 'Volpino Italiano')
    Raza.create(tipo: 'perro', nombre: 'Weimaraner')
    Raza.create(tipo: 'perro', nombre: 'Welsh springer spaniel')
    Raza.create(tipo: 'perro', nombre: 'Welsh Corgi Cardigan')
    Raza.create(tipo: 'perro', nombre: 'Welsh Corgi Pembroke')
    Raza.create(tipo: 'perro', nombre: 'Welsh terrier')
    Raza.create(tipo: 'perro', nombre: 'West highland white terrier')
    Raza.create(tipo: 'perro', nombre: 'Whippet')
    Raza.create(tipo: 'perro', nombre: 'Wirehaired solvakian pointer')
    Raza.create(tipo: 'perro', nombre: 'Xoloitzcuintle')
    Raza.create(tipo: 'perro', nombre: 'Yorkshire Terrier')

  end

  def down
    execute("DELETE FROM razas WHERE tipo='perro'")
  end
end
